# Base configs
#baseurl: "https://snappybara.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Steven Lao"
subtitle: "See the world through my eyes!"
author: "Steven Lao"
header:
 title: "Photography"
 subtitle: "by Steven Lao"
footer:
 name: "Hey there, my name is Steven"
 bio: "I am a software developer and a capybara lover from Canada. I enjoy taking pictures of sports, nature and animals!"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://instagram.com/snappy.bara/"
  linkedin: "https://linkedin.com/in/lao-a-steven"
  github: "https://github.com/laosteven"
